<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Discount;

class DiscountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create realistic discounts for jewelry business in the Philippines
        $discounts = [
            [
                'name' => 'New Customer Welcome',
                'code' => 'NEW_CUSTOMER',
                'amount' => 2000.00,
                'type' => 'fixed',
                'description' => 'Welcome discount for first-time customers',
                'valid_from' => now(),
                'valid_until' => now()->addMonths(6),
                'usage_limit' => 100,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Bulk Purchase Discount',
                'code' => 'BULK_PURCHASE',
                'amount' => 15.00,
                'type' => 'percentage',
                'description' => 'Discount for bulk jewelry purchases',
                'valid_from' => now(),
                'valid_until' => now()->addMonths(3),
                'usage_limit' => 50,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Loyalty Customer Discount',
                'code' => 'LOYALTY',
                'amount' => 8.00,
                'type' => 'percentage',
                'description' => 'Discount for loyal and returning customers',
                'valid_from' => now(),
                'valid_until' => null,
                'usage_limit' => null,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Christmas Holiday Sale',
                'code' => 'CHRISTMAS_SALE',
                'amount' => 1000.00,
                'type' => 'fixed',
                'description' => 'Special Christmas season discount',
                'valid_from' => now(),
                'valid_until' => now()->addMonths(2),
                'usage_limit' => 200,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'VIP Customer Premium',
                'code' => 'VIP_PREMIUM',
                'amount' => 20.00,
                'type' => 'percentage',
                'description' => 'Premium discount for VIP customers',
                'valid_from' => now(),
                'valid_until' => null,
                'usage_limit' => null,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Senior Citizen Discount',
                'code' => 'SENIOR_CITIZEN',
                'amount' => 12.00,
                'type' => 'percentage',
                'description' => 'Special discount for senior citizens',
                'valid_from' => now(),
                'valid_until' => null,
                'usage_limit' => null,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'PWD Discount',
                'code' => 'PWD',
                'amount' => 10.00,
                'type' => 'percentage',
                'description' => 'Discount for Persons with Disabilities',
                'valid_from' => now(),
                'valid_until' => null,
                'usage_limit' => null,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Employee Discount',
                'code' => 'EMPLOYEE',
                'amount' => 25.00,
                'type' => 'percentage',
                'description' => 'Employee discount for staff members',
                'valid_from' => now(),
                'valid_until' => null,
                'usage_limit' => null,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Corporate Discount',
                'code' => 'CORPORATE',
                'amount' => 18.00,
                'type' => 'percentage',
                'description' => 'Corporate client discount for business purchases',
                'valid_from' => now(),
                'valid_until' => null,
                'usage_limit' => null,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Valentine\'s Day Special',
                'code' => 'VALENTINES',
                'amount' => 500.00,
                'type' => 'fixed',
                'description' => 'Valentine\'s Day special discount',
                'valid_from' => now(),
                'valid_until' => now()->addMonths(1),
                'usage_limit' => 150,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Mother\'s Day Special',
                'code' => 'MOTHERS_DAY',
                'amount' => 800.00,
                'type' => 'fixed',
                'description' => 'Mother\'s Day special discount',
                'valid_from' => now(),
                'valid_until' => now()->addMonths(1),
                'usage_limit' => 100,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Father\'s Day Special',
                'code' => 'FATHERS_DAY',
                'amount' => 600.00,
                'type' => 'fixed',
                'description' => 'Father\'s Day special discount',
                'valid_from' => now(),
                'valid_until' => now()->addMonths(1),
                'usage_limit' => 100,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Birthday Special',
                'code' => 'BIRTHDAY',
                'amount' => 10.00,
                'type' => 'percentage',
                'description' => 'Birthday month special discount',
                'valid_from' => now(),
                'valid_until' => null,
                'usage_limit' => null,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Anniversary Special',
                'code' => 'ANNIVERSARY',
                'amount' => 15.00,
                'type' => 'percentage',
                'description' => 'Wedding anniversary special discount',
                'valid_from' => now(),
                'valid_until' => null,
                'usage_limit' => null,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Referral Bonus',
                'code' => 'REFERRAL',
                'amount' => 1000.00,
                'type' => 'fixed',
                'description' => 'Referral bonus for bringing new customers',
                'valid_from' => now(),
                'valid_until' => null,
                'usage_limit' => null,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Clearance Sale',
                'code' => 'CLEARANCE',
                'amount' => 30.00,
                'type' => 'percentage',
                'description' => 'Clearance sale discount for discontinued items',
                'valid_from' => now(),
                'valid_until' => now()->addMonths(3),
                'usage_limit' => 300,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Flash Sale',
                'code' => 'FLASH_SALE',
                'amount' => 25.00,
                'type' => 'percentage',
                'description' => 'Limited time flash sale discount',
                'valid_from' => now(),
                'valid_until' => now()->addDays(7),
                'usage_limit' => 50,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Member Discount',
                'code' => 'MEMBER',
                'amount' => 5.00,
                'type' => 'percentage',
                'description' => 'Member discount for registered customers',
                'valid_from' => now(),
                'valid_until' => null,
                'usage_limit' => null,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Early Bird Discount',
                'code' => 'EARLY_BIRD',
                'amount' => 12.00,
                'type' => 'percentage',
                'description' => 'Early bird discount for advance purchases',
                'valid_from' => now(),
                'valid_until' => now()->addMonths(2),
                'usage_limit' => 75,
                'used_count' => 0,
                'active' => true,
            ],
            [
                'name' => 'Cash Payment Discount',
                'code' => 'CASH_PAYMENT',
                'amount' => 3.00,
                'type' => 'percentage',
                'description' => 'Discount for cash payments',
                'valid_from' => now(),
                'valid_until' => null,
                'usage_limit' => null,
                'used_count' => 0,
                'active' => true,
            ],
        ];

        foreach ($discounts as $discount) {
            Discount::firstOrCreate(['code' => $discount['code']], $discount);
        }
    }
}