import {
  faUser,
  faLock,
  faEnvelope,
  faEye,
  faEyeSlash,
  faSignIn,
  faSignOut,
  faKey,
  faArrowLeft,
  faPaperPlane,
  faCheck,
  faExclamationTriangle,
  faSpinner,
  faGem,
  faShieldAlt,
  faChartLine,
  faFileInvoice,
  faCreditCard,
  faHistory,
  faDownload,
  faUpload,
  faSearch,
  faFilter,
  faCalendar,
  faDollarSign,
  faClock,
  faCheckCircle,
  faTimesCircle,
  faExclamationCircle,
  faInfoCircle,
  faEdit,
  faTrash,
  faPlus,
  faMinus,
  faBars,
  faTimes,
  faHome,
  faUserCircle,
  faCog,
  faBell,
  faQuestionCircle
} from '@fortawesome/free-solid-svg-icons';

export const solidIconMap = {
  user: faUser,
  lock: faLock,
  envelope: faEnvelope,
  eye: faEye,
  eyeSlash: faEyeSlash,
  signIn: faSignIn,
  signOut: faSignOut,
  key: faKey,
  arrowLeft: faArrowLeft,
  paperPlane: faPaperPlane,
  check: faCheck,
  exclamationTriangle: faExclamationTriangle,
  spinner: faSpinner,
  gem: faGem,
  shieldAlt: faShieldAlt,
  chartLine: faChartLine,
  fileInvoice: faFileInvoice,
  creditCard: faCreditCard,
  history: faHistory,
  download: faDownload,
  upload: faUpload,
  search: faSearch,
  filter: faFilter,
  calendar: faCalendar,
  dollarSign: faDollarSign,
  clock: faClock,
  checkCircle: faCheckCircle,
  timesCircle: faTimesCircle,
  exclamationCircle: faExclamationCircle,
  infoCircle: faInfoCircle,
  edit: faEdit,
  trash: faTrash,
  plus: faPlus,
  minus: faMinus,
  bars: faBars,
  times: faTimes,
  home: faHome,
  userCircle: faUserCircle,
  cog: faCog,
  bell: faBell,
  questionCircle: faQuestionCircle
};