// src/utils/solidIcons.js

import {
  faPlus,
  faTrash,
  faEdit,
  faSave,
  faTimes,
  faCheck,
  faSearch,
  faDownload,
  faUpload,
  faEye,
  faEyeSlash,
  faUser,
  faUsers,
  faLock,
  faSignOutAlt,
  faCog,
  faBell,
  faEnvelope,
  faHome,
  faInfoCircle,
  faExclamationTriangle,
  faCalendarAlt,
  faChevronDown,
  faChevronUp,
  faAngleDown,
  faAngleUp,
  faArrowRight,
  faArrowLeft,
  faFileAlt,
  faChartBar,
  faClock,
  faFileExport,
  faRotateLeft,
  faRotateRight,
  faImage,
  faSignInAlt,
  faQuestionCircle,
  faPhone,
  faBuilding,
  faGlobe,
  faFax,
  faList,
  faPrint,
  faCashRegister,
  faFilter,
  faSyncAlt,
  faDollarSign,
  faChartLine,
  faChartPie,
  faExclamationCircle,
  faCheckCircle,
  faTimesCircle,
  faCalculator,
  faTag,
  faPercent,
  faCreditCard,
  faHistory
} from '@fortawesome/free-solid-svg-icons';

export const solidIconMap = {
  plus: faPlus,
  trash: faTrash,
  edit: faEdit,
  save: faSave,
  times: faTimes,
  check: faCheck,
  search: faSearch,
  download: faDownload,
  upload: faUpload,
  eye: faEye,
  eyeslash: faEyeSlash,
  user: faUser,
  users: faUsers,
  lock: faLock,
  signout: faSignOutAlt,
  cog: faCog,
  bell: faBell,
  envelope: faEnvelope,
  home: faHome,
  info: faInfoCircle,
  warning: faExclamationTriangle,
  calendar: faCalendarAlt,
  chevrondown: faChevronDown,
  chevronup: faChevronUp,
  angleDown: faAngleDown,
  angleUp: faAngleUp,
  arrowright: faArrowRight,
  arrowleft: faArrowLeft,
  file: faFileAlt,
  chart: faChartBar,
  clock: faClock,
  fileexport: faFileExport,
  rotateLeft: faRotateLeft,
  rotateRight: faRotateRight,
  image: faImage,
  signIn: faSignInAlt,
  questionCircle: faQuestionCircle,
  phone: faPhone,
  building: faBuilding,
  globe: faGlobe,
  list: faList,
  print: faPrint,
  cashRegister: faCashRegister,
  filter: faFilter,
  refresh: faSyncAlt,
  dollarSign: faDollarSign,
  chartLine: faChartLine,
  chartPie: faChartPie,
  exclamationCircle: faExclamationCircle,
  checkCircle: faCheckCircle,
  timesCircle: faTimesCircle,
  calculator: faCalculator,
  tag: faTag,
  percent: faPercent,
  calendarAlt: faCalendarAlt,
  creditCard: faCreditCard,
  history: faHistory
};
